version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:8u242-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git-lfs
          git lfs pull
          ./gradlew build
